---
title: "Checking Python and R exercises"
author: "Nischal Shrestha"
output: learnr::tutorial
runtime: shiny_prerendered
description: > 
  This is a demo of checking both Python and R exercises.
---

```{r setup, include = FALSE}
library(learnr)
library(gradethis)
library(tidyverse)
library(reticulate)
library(pygradethis)
# exercise checker for R exercises
tutorial_options(exercise.checker = gradethis::grade_learnr)
d <- 2
```

# Python

```{python df}
mpg = r.mpg
mpg
```

The expected answer is the `mpg` dataset from R. This exercise uses `pygradethis::py_grade_learnr` for checking solution.

```{python ex1, exercise=TRUE, exercise.setup = "df", exercise.checker = pygradethis::py_grade_learnr}
mpg
```

```{python ex1-check}
python_grade_result(
  python_pass_if(mpg, "You also got the mpg dataframe!"),
  python_fail_if(None, "")
)
```

# R

```{r ex2, exercise=TRUE}
mpg
```

```{r ex2-code-check}
gradethis::grade_code(
  correct = "good job",
)
```

```{r ex2-solution}
mpg
```

```{r ex2-check}
gradethis::grade_result(
  pass_if(~ identical(.result, mpg), "You also got the mpg dataframe"),
  fail_if(~ TRUE, "Oops!")
)
```


